services:
  - type: web
    name: verceldingsdabumsda
    env: node
    buildCommand: chmod +x ./find-package.sh && ./find-package.sh && npm ci && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production 