services:
  - type: web
    name: verceldingsdabumsda
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production 